language: java
jdk:
- oraclejdk8
branches:
  only:
  - master
  - dev
cache:
  directories:
  - "$HOME/.m2/repository"
env:
- DB_URL=jdbc:postgresql://localhost:5432/travis_test DB_USER=tester DB_PASSWORD=travis_test
services:
- postgresql
install:
- mvn validate
before_script:
- psql -c "CREATE USER tester WITH SUPERUSER PASSWORD 'travis_test';" -U postgres
- psql -c "CREATE DATABASE travis_test;" -U postgres
- psql -c "GRANT ALL ON DATABASE travis_test TO tester;" -U postgres
script:
- mvn clean install
deploy:
  provider: script
  script: "./deploy.sh 5.2.76.53"
  skip_cleanup: true
  on:
    branch:
    - master
    - dev
before_install:
- openssl aes-256-cbc -K $encrypted_bd0a761beaf9_key -iv $encrypted_bd0a761beaf9_iv -in server.enc -out $HOME/.ssh/server -d
